from nexus.tasks.changelog import _format_release_body


def test_empty_sections_omitted() -> None:
    body = _format_release_body(prev="v0.1.0", tag="v0.2.0", sections={})
    assert "## v0.2.0" in body
    assert "_Changes since v0.1.0_" in body
    assert "Features" not in body
    assert "Fixes" not in body
    assert "Generated by Nexus." in body


def test_full_sections_render_in_priority_order() -> None:
    body = _format_release_body(
        prev="v0.1.0",
        tag="v0.2.0",
        sections={
            "feat": ["Add Skill diffing"],
            "fix": ["Cache invalidation on edit"],
            "breaking": ["Drop /v1/skills"],
            "other": ["README typo"],
        },
    )
    breaking_idx = body.index("### Breaking changes")
    features_idx = body.index("### Features")
    fixes_idx = body.index("### Fixes")
    other_idx = body.index("### Other")
    assert breaking_idx < features_idx < fixes_idx < other_idx


def test_initial_release_omits_since_line() -> None:
    body = _format_release_body(prev=None, tag="v0.1.0", sections={"feat": ["initial"]})
    assert "_Changes since" not in body
